<?php

return array(
  'language' => 'Sprache',
  'german' => 'Deutsch',
  'english' => 'Englisch',
  'settings' => 'Einstellungen',
  'home' => 'Home',
  'name' => 'Name',
  'loginfailed' => 'Login fehlgeschlagen. Dein Username oder Passwort war falsch.',
  'logout' => 'Abmelden',
  'foldername' => 'Ordnername',
  'addfolder' => 'Ordner hinzufügen',
  'newfolder' => 'Neuer Ordner',
  'folders' => 'Ordner',
  'password' => 'Passwort',
  'addpassword' => 'Passwort hinzufügen',
  'newpassword' => 'Neues Passwort',
  'passwordrepeat' => 'Passwort wiederholen',
  'dashboard' => 'Dashboard',
  'foldercreatesuccessful' => 'Ordner wurde erfolgreich angelegt.',
  'foldercreateerror' => 'Ordner konnte nicht angelegt werden.',
  'installsetup' => 'Installation',
  'login' => 'Anmelden',
  'username' => 'Benutzername',
  'upperfolder' => 'Übergeordneten Ordner wählen',
  'label' => 'Bezeichnung',
  'description' => 'Beschreibung',
  'editpassword' => 'Passwort bearbeiten',
  'editfolder' => 'Ordner bearbeiten',
  'nopermissions' => 'Sie haben keine Berechtigung das zu tun.',
  'nolabelset' => 'Es wurde keine Bezeichnung angegeben. Das ist ein Pflichtfeld.',
  'nopasswordset' => 'Es wurde kein Passwort angegeben. Das ist ein Pflichtfeld.',
  'users' => 'Benutzer',
  'permissions' => 'Rechte',
  'refreshfolder' => 'Ordner aktualisieren',
  'languageandtime' => 'Sprache und Zeit',
  'timezone' => 'Zeitzone',
  'normallanguage' => 'Standard Sprache',
  'languagepath' => 'Sprachpfad',
  'paths' => 'Pfade',
  'designpath' => 'Designs',
  'toggleall' => 'Alle aufklappen',
  'deletefolder' => 'Ordner löschen',
  'deletepassword' => 'Passwort löschen',
  'yesdelete' => 'Ja, löschen',
  'nodelete' => 'Nein, abbrechen',
);
