<?php

return array(
  'language' => 'Language',
  'german' => 'German',
  'english' => 'English',
  'settings' => 'Settings',
  'home' => 'Home',
  'name' => 'name',
  'loginfailed' => 'Login failed. Your username or password was wrong.',
  'logout' => 'Logout',
  'foldername' => 'Folder name',
  'addfolder' => 'Add folder',
  'newfolder' => 'New folder',
  'folders' => 'Folder',
  'password' => 'Password',
  'addpassword' => 'Add password',
  'newpassword' => 'New password',
  'passwordrepeat' => 'Repeat Password',
  'dashboard' => 'Dashboard',
  'foldercreatesuccessful' => 'Folder was successfully created.',
  'foldercreateerror' => 'Folder could not be created successfully.',
  'installsetup' => 'Install setup',
  'login' => 'Login',
  'username' => 'Username',
  'upperfolder' => 'Select parent folder',
  'label' => 'Label',
  'description' => 'Description',
  'editpassword' => 'Edit password',
  'nopermissions' => 'You have no permissions to do this',
  'nolabelset' => 'No label was set. This is mandatory.',
  'nopasswordset' => 'No password was set. This is mandatory.',
  'users' => 'Users',
  'permissions' => 'Permissions',
  'refreshfolder' => 'Refresh folders',
  'languageandtime' => 'Language and time',
  'time' => 'Time',
  'timezone' => 'Timezone',
  'normallanguage' => 'Normal Language',
  'languagepath' => 'Path to languages',
  'paths' => 'Paths',
  'designpath' => 'Designs',
);
